[project]
name = "chat-seguran-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=41.0.0",
    "pynacl>=1.6.0",
    "websockets>=11.0.0",
]
